### ISSUE TITLE
system.log | main critical error

### ISSUE THREAD

**Issue by cap340** [UrbanSurfers/magento-2#1]
main critical error : 
L’élément 'product.info.options' possède déjà un enfant avec l’alias XXXX

Comment 'product.info.options' section in 
design/frontend/Urban/urban/Magento_Catalog/layout/catalog_product_view.xml

**Comment by UrbanSurfers** [comment]
#https://github.com/UrbanSurfers/magento-2/commit/ec29b4e9263e62b9ab6792e13c9273fc37de46df
